// root-layout.test.tsx
import React from 'react';
import { render, screen } from '@testing-library/react';
import RootLayout from '@/app/layout'; // Update the import path as needed
import { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Provider from './Provider';

// Mock next/font/google
jest.mock('next/font/google', () => ({
  Geist: jest.fn(() => ({
    variable: '--font-geist-sans',
    className: 'geist-sans',
  })),
  Geist_Mono: jest.fn(() => ({
    variable: '--font-geist-mono',
    className: 'geist-mono',
  })),
}));

// Mock the Provider component
jest.mock('./Provider', () => 
  ({ children }: { children: React.ReactNode }) => (
    <div data-testid="provider">{children}</div>
  )
);

describe('RootLayout', () => {
  it('should export the correct metadata', () => {
    const metadata: Metadata = require('@/app/layout').metadata;
    
    expect(metadata.title).toBe('Create Next App');
    expect(metadata.description).toBe('Generated by create next app');
    expect(metadata.robots).toEqual({
      index: true,
      follow: true,
    });
  });

 

  it('renders children correctly', () => {
    const testText = 'Test Child Content';
    render(
      <RootLayout>
        <div>{testText}</div>
      </RootLayout>
    );

    expect(screen.getByText(testText)).toBeInTheDocument();
  });

  it('matches snapshot', () => {
    const { asFragment } = render(
      <RootLayout>
        <div>Test Child</div>
      </RootLayout>
    );
    expect(asFragment()).toMatchSnapshot();
  });

  it('initializes fonts correctly', () => {
    render(
      <RootLayout>
        <div>Test</div>
      </RootLayout>
    );

    expect(Geist).toHaveBeenCalledWith({
      variable: '--font-geist-sans',
      subsets: ['latin'],
    });

    expect(Geist_Mono).toHaveBeenCalledWith({
      variable: '--font-geist-mono',
      subsets: ['latin'],
    });
  });
});